server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:mx342/microservicecloud-config.git
          uri: https://github.com/mx342/microservicecloud-config.git
          search-paths: config-repo
          username: mx342 #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: liyazheng222 #密码