server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: cyjz-microcloud
  company.name: www.debuggg.top
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
zuul:
  routes:
    mydept.serviceId: microservicecloud-config-dept-client
    mydept.path: /mydept/**
  ignored-services: "*" #禁用真实名字，如果要忽略全部，可以使用“*”
  prefix: /cyjz

